### ISSUE TITLE
CI/CD 구축

### ISSUE THREAD

**Issue by BaeKY** [BaeKY/kube-ops#3]
![cicd-flow](https://user-images.githubusercontent.com/20514503/210544543-16e2869d-21e5-4093-90fe-901bf4c0c69b.png)

**Comment by BaeKY** [comment]
> #2 덕분에 ingress에 host만 설정해도 local에서 잘 접근된다(ArgoCD UI)
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/20514503/210550243-8dbf5046-ae85-4be7-8e59-3318bf2fc4b9.png">

**Comment by BaeKY** [comment]
## Certificate 생성시 CertificateRequest가 Pending에서 안넘어갈때
- https://cert-manager.io/docs/troubleshooting/acme/#dns01-troubleshooting

## Overview
- 내 MacBook에서 k8s 구동중. k8s에 CoreDNS를 올려 MacBook자체 DNS서버로 이용중
- cert-manager는 acme를 통해 ClusterIssuer를 생성해둔 상태
- Split Horizon DNS 구성: letsencrypt 인증서를 MacBook의 K8S에서 사용함
- 아래와 같은 설정으로 Certificate을 생성하면 계속 kube-system의 core-dns로 Request(생성된 Challenge가 하는 요청)가 감.
  ```YAML
  apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: myapp-tls
    namespace: default
  spec:
    dnsNames:
      - myapp.lab9.cloud
    issuerRef:
      kind: ClusterIssuer
      name: acme-issuer
    secretName: myapp-tls
  ```

## Solution
- https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
